liveConfig:
    - !!models.LiveConfig
         key:                   orders_sender_email_address
         valuestring:           contact@hometime.fr

    - !!models.LiveConfig
         key:                   notify_team_by_email_active
         valueboolean:          true

    - !!models.LiveConfig
         key:                   notify_team_by_email_to_1
         valuestring:           contact@hometime.fr

    - !!models.LiveConfig
         key:                   notify_team_by_email_to_how_many
         valuelong:             1

    - !!models.LiveConfig
         key:                   mailjet_api_key
         valuestring:           aa98fac1ba34a8ae1c25eff67b4fe100

    - !!models.LiveConfig
         key:                   mailjet_secret_key
         valuestring:           6034d97e2f61ef55aba22a48f67c4607

    - !!models.LiveConfig
         key:                   sendinblue_api_key
         valuestring:           aa98fac1ba34a8ae1c25eff67b4fe100

    - !!models.LiveConfig
         key:                   sendinblue_partner_key
         valuestring:           6034d97e2f61ef55aba22a48f67c4607

    - !!models.LiveConfig
         key:                   mailjet_from_email
         valuestring:           contact@hometime.fr

    - !!models.LiveConfig
         key:                   mailjet_from_name
         valuestring:           RaphaÃ«l de Hometime.fr

    - !!models.LiveConfig
         key:                   mailjet_sms_from_value
         valuestring:           Hometime.fr

    - !!models.LiveConfig
         key:                   mailjet_sms_token
         valuestring:           TOFILL

    - !!models.LiveConfig
         key:                   store_closed
         valueboolean:           true

    - !!models.LiveConfig
         key:                   store_closed_title_forced
         valuestring:           <b>Titre</b>

    - !!models.LiveConfig
         key:                   store_closed_message_forced
         valuestring:           <a href="/news">Messa<i>ge</i></a>

    - !!models.LiveConfig
         key:                   secret_key_for_pdf
         valuestring:           test

#Fin

