liveConfig:
    - !!models.LiveConfig
         key:                   mailjet_api_key
         valuestring:           aa98fac1ba34a8ae1c25eff67b4fe100

    - !!models.LiveConfig
         key:                   mailjet_secret_key
         valuestring:           b221e6fd91b81a04d25ec067127ea995

    - !!models.LiveConfig
         key:                   orders_sender_email_address
         valuestring:           contact@hometime.fr

#Fin

